version: '3.3'

services:
  mongo:
    image: mongo
    ports:
      - 27020:27017
    volumes:
      - ./data:/data/db
    #environment:
    #  MONGO_INITDB_ROOT_USERNAME: root
    #  MONGO_INITDB_ROOT_PASSWORD: password
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 27080:8081
  